default: &default
  serverUrl: ~
  debug: false
  loglevel: error
  outputDir: dist/
  manifestDir: dist/
  assetsUrl: ""

development:
  <<: *default
  loglevel: debug
  debug: true

production:
  <<: *default
  serverUrl: USAFE_SERVER_URL
  assetsUrl: http://localhost:8080
  loglevel: USAFE_LOG_LEVEL

